dist: xenial
language: node_js
node_js: node
cache: yarn
deploy:
  provider: npm
  on:
    tags: true
  skip_cleanup: true
  email:
    secure: AoSC0bArNPbSAEQYdfUK+iR3fidkS1iwTD2atnHk2nWLv0PXqZXq8dEs0f7wk8fX4DU2C1ztXtHqDFe9E5J08fWvfezQDRmjkShG+y1XRE2XRzoAKzH1hgkJjW5NO8oIqSMXgYM4VlMCme8SMnU/O8Ty8V4v0YoBj65/9q12G6iugJcmuGiOMipgh+MOp4ki0nw7EKSSvgggi/4PfwOEtjsdRv/covVlFGHM7q4GRWLBbXEcV/o2cmm8X288dfGoVfS4uxKC1ALAEROchGS+T4DMuXl/xl91jCjXRSWCKHof2BFujyRknswpRrwbZ/kmRU0rHlH5VmnIm07hlu0IXRVI0Icod8/xrE8MY5hPy1O8GZ3idnsxuXXOKDf2Hv6zc4mxdotXJ1voQTeywJIXT8I9KjpXbjIwahik3WcP8yKvOR3WHDebPgFUrRhOVn47JDx+ZlnYpqP1LXnWLSx1MLzXLFhObFk63RWJc9mFSQYdo3vc+8wUwfHCzoiNPMRcmlYQp/15qDkfBcKS1JSm9dOIbV6aSq5Fox5RWSuz1MougSDqTG6OmJ9oq7mpgvCLqmk3PszUgct0TuDfaDlMbBjzqsQ2KyyAwoHP7Vm1O8jncSO4uYxavC6fv5iFBQbnw4YL1BwxT7Nx2GJyVDEX7z1Qdpe0xgmSU843vxRuFwk=
  api_key:
    secure: rOPBiw4TqRY7MSrMq7EjEVel4PNblp8CcJvu6o2kgBC0ED8KMzH2kcvBkXfpETOOY0+1J7H0ebomilosM6T5CvcWGNWZks3aVTk7wDr53HOM9HN/Dl9qwlotXq7B/X/NWY8eLey02TSPR19naBUOK1v3mmi6HDDhlbmU4B0IqSTN0VIsyLQBAvIGz3SMTm55zrnbIgBZ5ktcFXyR8XEroa7ghXTzUmsHZEtgIZQJWzvOj/lVfky+D+c6oCngZ71rhGAng9w487bHVcHXW7nGoS3s95nxQau/8PbcMC94LMBlNUKMHKrxqGDyqhhGsaTVlMBBDA8qykF/JcL2AQp7mOK3qyLz/BkSgYxQxEhpjfdgYRUHeyGp6+DdsX3nTQlFEGobPaAvD4cEbh+k+tvnC1k0M0x2rL6NbouwF8pfYBlZcxOh0xfELyjZj8qpCsIG/rZJYCUF2KOltqHJMHY/HsuqGi2IoegnJZCGmoGvfyDTmQEVsduphOGI+wymEnYm7RUDWKJ9mNDKCUPEwF1A3sNzWk+6ieu4fNs6fWNfw5AOcHb7UO22QQn+CiyJEvBzVWAm16YHPXoEwxeIagCvb5Wju/G2ALLK6K2P7BKvJE4YdHebbp1OTGLoybPl/uA747i3THni/054RL/7PcqmQ1IMguKwYttIrycvIGSLZqk=
