group: travis_latest
language: node_js
node_js: node
cache: yarn

deploy:
  provider: npm
  on:
    tags: true
  skip_cleanup: true
  email:
    secure: AoSC0bArNPbSAEQYdfUK+iR3fidkS1iwTD2atnHk2nWLv0PXqZXq8dEs0f7wk8fX4DU2C1ztXtHqDFe9E5J08fWvfezQDRmjkShG+y1XRE2XRzoAKzH1hgkJjW5NO8oIqSMXgYM4VlMCme8SMnU/O8Ty8V4v0YoBj65/9q12G6iugJcmuGiOMipgh+MOp4ki0nw7EKSSvgggi/4PfwOEtjsdRv/covVlFGHM7q4GRWLBbXEcV/o2cmm8X288dfGoVfS4uxKC1ALAEROchGS+T4DMuXl/xl91jCjXRSWCKHof2BFujyRknswpRrwbZ/kmRU0rHlH5VmnIm07hlu0IXRVI0Icod8/xrE8MY5hPy1O8GZ3idnsxuXXOKDf2Hv6zc4mxdotXJ1voQTeywJIXT8I9KjpXbjIwahik3WcP8yKvOR3WHDebPgFUrRhOVn47JDx+ZlnYpqP1LXnWLSx1MLzXLFhObFk63RWJc9mFSQYdo3vc+8wUwfHCzoiNPMRcmlYQp/15qDkfBcKS1JSm9dOIbV6aSq5Fox5RWSuz1MougSDqTG6OmJ9oq7mpgvCLqmk3PszUgct0TuDfaDlMbBjzqsQ2KyyAwoHP7Vm1O8jncSO4uYxavC6fv5iFBQbnw4YL1BwxT7Nx2GJyVDEX7z1Qdpe0xgmSU843vxRuFwk=
  api_key:
    secure: W9/CPaMNr6xmUHT7CRuAjomx85qojVxMp86saxI5z8JXh2x11LP94N7Hzxq/iiQaRG9n3fMcibq2i1ChG3mBe8b5xbCbmBCfC4Szi3zUZcjA4Rbh1mGiSuHtZe151689xDwjnoRY0558NHZ3VV1lNfLOnBDccd/zc1tVBj5jdP7d5WtxT5DaWUe8b+8t7acEdOv00ESGawwjHMcP+X9WOGQ8OOwLUqK+sry2nBKDFTWPw/VyfnQK9j5pvUnRAqXNuvdJilp6AacAP21/EJiGm6XzrSiBhC14nwPLTg2rlv1f53O427sOnWIKxMObrZqTYNcvp4yBAqf9LxDTHUzTRWGltwJ8WqUYaSsqAOfO71bMvFWtxcyWQJhIDYwYcIEzy8hDwtt8//+7SQQxDVZt5d5y+VuCoYManQvLFspvONyEpHFGcqtb/vOWR9NicqCjjm3FNG53gk2UrBzbNtSFQoi6E8+7IiJJgTvdxmMG3r8zbkj05r1UzX0NoPVAcv4nBStOJDAYxRHO2yUutrN2bVEV7xcAq0QOPOVmXkiQE4BYMun2hpbISXOJr1MqaCaDjfGWSIOTVtva7ISGm9fRQ4CZPdGb+43wMyV88g03R2QrxofvhufPCgEHmM+vpJbg81SkfJMDcMAeHX5okVUQJsQYvx98I4/PknhgJizaJB4=
