dist: xenial
language: node_js
node_js: node
cache: yarn
env:
  global:
  - secure: Q1CpfVZN9cVf5djXvG9KfEOLmhnelYZHx9lTEDIWlYMI2qX8oEPqtRNlbm7DtRPnx8hu50NgckmJBl7ekmyKttqXczyL/wSWpeDSUlXL0nAR+hwm/cgaGU2P3HEk25cKleDRnFdTVpEuICbVYjKzNkiesl7FZmxD5QLX5Knbngm0uO8q9lyp03aUpTK48LbkP14xWgAugKmeLUPnPC5n1GmVzCuKqU2eGvu/7rVpatk5cp94t7XQDdiuSZ1QcoHMTrp3jIHQa6M9bX9hCdxLoYnB2in0HYQe7C+ICeZ8jz77+NFdtjf3EWx17725FPNv3SSa6mhVGaUU3ZzfxfjRoWjLi6htsbsXcZHxKNO1uK/7I95JJmgaHIy6u/FusB1HGJ9cTtCJL/ue0O54TTuvK58jA9Yk2uFomH9kP9naKivrUdcwjp9mYURnqP9OmRGDtD5eaIotNQTXXOMKFaOI8t+aKvtOQ7y7ZQwP1ww0cjkT3Ya+YQeqyv/xRfEMwMBbza/R4VegoqBPen0joAV0kHcSzW9CouppKxcaNGYHKD2IxgthdjT4K8WjvAYXPR3yf5lix3esnfttnEG5STHVW+c4CCI+VEWxm94WjPY+MzBR8b7VDqbPUqTAzTqjJYxuIKOwFUr+fL0Wt7xbUklX0qMswbDTS6gkPvDIcQ7Cd5M=
  - secure: qljFLOUvRDSuRB7nfcXXAg65M/1kgzBrWclIQrSpsHGpUT99sJonMf6npceop+r5lfAGZgEWGL+lapgomx3NwPOwDyfwC39MAj75wcwmdVKaCkWHhY+9O+5Ta/Lg/jKTm3blMlt/9OD06LE/6F39l20NBy240PAgkpfUBO0/W3lvxm8BB41GXpCpnqvZeOHy7+Mrg5bI6/n/HMY1hI25Ho9s6kGg9b7vT/9N1cKMRksyZgssJ+7OMOu3sV3TG1E/cy1mueaCMqYcPmHUEebCZP+2DnXGF/k/kO/cVIh6aDpf/OwZwKu5KW4tyc4K5eVm5zTWhgU2Y1WxORh9oEqHng77f9KQ6pqXq+4D7/CNbtKZXInbxWT4gnZSSVQxDrDlrarttQi7OkxFfFkl+uzwbH2qzF0mKc/6XUfuuDRGhqgdZQ92XjCBKSv46RJe7rCInzzgLI2wld5dxUg+9PfrxbzJl7gy0rEW6ZPvBZw2B9uPoW77DImKZEGHV9VfCx2WA6Y1UxmuwK4WX0aInj8Q18JB3qS+mO3CvgvJ163FRMrV3OHDImfC512PR4duJuRrA4Kd64biv7Yfs56NVfk7ugbP5VKndO79YN5c42aKuR/iE6FB4GS8iV9zwrHJU0ekziLTfdPuSsA9KpfWxbZ1V3vuoPvY1mX+U+KMEf2Yt/M=
if: tag IS blank
deploy:
  provider: script
  skip_cleanup: true
  script:
  - yarn release
